#!/bin/bash

# add obstacle
#rosrun gazebo_ros spawn_model -file `rospack find youbot_description`/urdf/youbot_obstacle/obstacle.urdf  -urdf -x 1.3 -y 0.8 -z 1.0 -model box -robot_namespace youbot

roslaunch youbot_navigation trajectory.launch
