#! /bin/bash
sudo killall gzserver
sudo killall gzclient
# sudo killall rviz
sudo killall roscore
sudo killall rosmaster

roslaunch youbot_gazebo_robot youbot.launch

rosrun laser_processor laser_processor 