#! /bin/bash
sudo killall gzserver
sudo killall gzclient
sudo killall rviz
sudo killall roscore
sudo killall rosmaster
# find pids through awk and kill jic
ps ax | grep laser_processor | awk '{print $1}' | xargs kill -9
ps ax | grep "traj_opt.py" | awk '{print $1}' | xargs kill -9
ps ax | grep "spawn_model" | awk '{print $1}' | xargs kill -9

roslaunch youbot_gazebo_robot youbot.launch & sleep 5; \
 rosrun gazebo_ros spawn_model -file \
 `rospack find youbot_description`/urdf/youbot_obstacle/obstacle.urdf \
  -urdf -x 1.3 -y 0.8 -z 1.0 -model box -robot_namespace youbot 

